# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693d1d1d97299e421ca64b9e693ad0a59d87948743bff2ee6248f0a15de00dcbca8a57f57ffb0b78b783e159429840d7ab58c7d1a5f3cfddd2433497a91ae868

test:
  secret_key_base: 03ed0e89d91e54bd0a7b814071534e57b115377d4d17a63c5871567574895a1382466b3efb27dc6d74a3290a333e3c120c3a0d5f76edaa33a180137c9f84205f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
